name: cd
on:
  push:
    branches:    
      - main

env:
  CI: "true"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --check-files
      - name: Unit Tests
        run: yarn test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --check-files
      - name: build
        run: yarn build
      - name: Upload cloud assemblies
        uses: actions/upload-artifact@v3
        with:
          name: cdk.out
          path: cdk.out
  
  deploy-staging:
    runs-on: ubuntu-latest
    needs: [test, build]
    environment: staging
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --check-files
      - name: Download cloud assemblies
        uses: actions/download-artifact@v3
        with:
          name: cdk.out
          path: cdk.out
      - name: Deploy staging environment
        run: npx cdk deploy workshop-engine-staging -o cdk.out

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: prod
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --check-files
      - name: Download cloud assemblies
        uses: actions/download-artifact@v3
        with:
          name: cdk.out
          path: cdk.out
      - name: Deploy prod environment
        run: npx cdk deploy workshop-engine-prod -o cdk.out

