name: cd
on:
  push:
    branches:    
      - main

env:
  CI: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --check-files
      - name: build
        run: yarn build
      - name: Upload cloud assemblies
        uses: actions/upload-artifact@v3
        with:
          name: cdk.out
          path: cdk.out
  
  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: staging
      url: ${{ steps.set-environment-url.outputs.environment_url }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --check-files
      - name: Download cloud assemblies
        uses: actions/download-artifact@v3
        with:
          name: cdk.out
          path: cdk.out
      - name: Deploy staging environment
        run: npx cdk deploy workshop-engine-staging -a cdk.out -O outputs.json --require-approval never
      - name: Set environment URL
        id: set-environment-url
        run: echo "::set-output name=environment_url::$(cat outputs.json | jq -r '."workshop-engine-staging" | to_entries | map(select(.key | startswith("GraphQLApiEndpoint")))[0].value')"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: prod
      url: ${{ steps.set-environment-url.outputs.environment_url }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --check-files
      - name: Download cloud assemblies
        uses: actions/download-artifact@v3
        with:
          name: cdk.out
          path: cdk.out
      - name: Deploy prod environment
        run: npx cdk deploy workshop-engine-prod -a cdk.out -O outputs.json --require-approval never
      - name: Set environment URL
        id: set-environment-url
        run: echo "::set-output name=environment_url::$(cat outputs.json | jq -r '."workshop-engine-prod" | to_entries | map(select(.key | startswith("GraphQLApiEndpoint")))[0].value')"

