name: report to slack
on:
  workflow_run:
    workflows: [cd]
    types:
      - completed

jobs:
  report_failure:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Report to slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "Workshop Engine Deployment failed! \n\n See: ${{ github.event.workflow_run.html_url }}"
            }
